### ISSUE TITLE
return all synonyms of an accepted name

### ISSUE THREAD

**Issue by iskanderun** [ojalaquellueva/TNRSapi#11]
I have a feature request, which is to return all synonyms of an accepted name. This would allow a user to see if they could get more observations by including synonyms. Depending on how this is implemented, it could give information about how many observations are within each category, so that the user can compare those numbers to the number of observations returned just by querying the accepted name. A command like BIEN::bien.synonyms("speciesname genusname") could return a table like this:

NAME                 ACCEPTED         SOURCE           NUMBER OF OBSERVATIONS            MOST CURRENT OBSERVATION
name_1               yes                      PWO                  12280                                                   2020
name_2              yes                      Tropicos            542                                                       1984
name_3              no                        -                         231                                                       1887

and so on.

**Comment by ojalaquellueva** [comment]
@iskanderun OK, will scope this out. I believe this is also a (dependent) feature request for RBIEN and RtodoBIEN

**Comment by ojalaquellueva** [comment]
@iskanderun This is actually a request for two features: (1) a synonym lookup using the TNRS (in scope), and (2) a count of observations in the BIEN data, including synonyms retrieved by the TNRS (out of scope; observations have nothing to do with the TNRS). (1) is a dependency for (2). I am working on (1). In the meantime, I suggest you add (2) as an RBIEN feature request to the [RBIEN repository](https://github.com/bmaitner/RBIEN). @bmaitner, take note.

**Comment by ojalaquellueva** [comment]
Resolved as new API call 'syn', also available via RTNRS as "Get synonyms" processing mode.
