### ISSUE TITLE
name leads to errors

### ISSUE THREAD

**Issue by shandongfx** [ojalaquellueva/TNRSapi#2]
Symplocos tinctoria L'Hér.

**Comment by shandongfx** [comment]
pass this name alone will be fine
           V1                             V2
781841 Monniera monniera (L.) Britton

But, pass two names together would lead to an error
           V1                             V2
781841 Monniera monniera (L.) Britton
781842      Xylosma litoralis Däniker

Error: lexical error: invalid character inside string.
          ame_matched":"Monniera monnier a","Name_score":"1","Name_mat
                     (right here) ------^

**Comment by ojalaquellueva** [comment]
Issue was carriage return (\r) embedded in the specific epithet between the "r" and "a" in name "Monniera monniera (L.) Britton" in the TNRS database. I.e., "Monniera monnier\ra". A total of 2 names out of 2,010,595 names total in tables "name" and "splist_genlist_combined" contained carriage returns. I've removed all carriage returns. Name "Monniera monniera (L.) Britton" no longer triggers this error.
